# Generated by Django 3.1.7 on 2021-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoParcheggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('temperatura', models.IntegerField()),
                ('umidita', models.IntegerField()),
                ('meteo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('data', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=50)),
                ('qrCode', models.CharField(max_length=64)),
            ],
        ),
    ]
