# Generated by Django 3.1.7 on 2021-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcheggio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='qrCode',
            field=models.CharField(max_length=256),
        ),
    ]
