# Generated by Django 3.1.7 on 2021-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcheggio', '0002_auto_20210430_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoparcheggio',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
